### different type of multiplicaton

- Vector * Vector 
   * it is considered as neurons 
- Vector * Matrix
    * it is considered as layers
- Matrix * Matrix
    * it is considered as batch.


Using numpy build neurons .

In [3]:
import numpy as np 
inputs = [1,2,3,4]
weights = [0.2,0.8,-0.5,1]
bias = 2
output = np.dot(inputs, weights) + bias
print(output)

6.3


Using Numpy to build layers.

In [4]:
import numpy as np
inputs = [1,2,3,4]
weights = [[0.2,0.8,-0.5,1],
           [0.5,0.1,-0.3,0.7],
           [0.9,0.4,0.2,0.5]]
bias = [2,3,0.5]
output = np.dot(weights, inputs) + bias
print(output)

[6.3 5.6 4.8]


Using Numpy build batch of data

In [7]:
inputs =[[1,2,3,4],
         [2,3,4,5],
         [3,4,5,6]]
weights = [[0.2,0.8,-0.5,1],
           [0.5,0.1,-0.3,0.7],  
           [0.9,0.4,0.2,0.5]]
bias = [2,3,0.5]
output = np.dot( np.array(inputs),np.array(weights).T) + np.array(bias)
print(output)

[[6.3 5.6 4.8]
 [7.8 6.6 6.8]
 [9.3 7.6 8.8]]


now adding more layers 